### ISSUE TITLE
Move `TrustRegion` structure to SolverTools.jl

### ISSUE THREAD

**Issue by tmigot** [JuliaSmoothOptimizers/AdaptiveRegularization.jl#92]
and add SolverTools.jl in deps.
The structure is here: https://github.com/JuliaSmoothOptimizers/AdaptiveRegularization.jl/blob/main/src/utils/utils.jl

**Comment by Jay-sanjay** [comment]
Hello @tmigot sir, I would be happy to work on this issue. I see you wanted to move this https://github.com/JuliaSmoothOptimizers/AdaptiveRegularization.jl/blob/main/src/utils/utils.jl#L1-L110 
Can you please tell where exactly it must be moved here https://github.com/JuliaSmoothOptimizers/SolverTools.jl/tree/main/src

**Comment by tmigot** [comment]
In the folder https://github.com/JuliaSmoothOptimizers/SolverTools.jl/tree/main/src/trust-region there is already two structures that resembles:
- TRONTrustRegion https://github.com/JuliaSmoothOptimizers/SolverTools.jl/blob/main/src/trust-region/tron-trust-region.jl
- TrustRegion https://github.com/JuliaSmoothOptimizers/SolverTools.jl/blob/main/src/trust-region/basic-trust-region.jl

The idea would be to rename the structure here in ARTrustRegion (for Adaptive Regularization Trust Region) in the folder, include is in this file https://github.com/JuliaSmoothOptimizers/SolverTools.jl/blob/main/src/trust-region/trust-region.jl and add it to the unit tests.
